import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { jwtVerify } from 'jose';
import { z } from 'zod';

const linkSchema = z.object({
  inviteCode: z.string().min(1),
});

/** Returns the session secret as Uint8Array — throws if not configured. */
function getSessionSecret(): Uint8Array {
  const secret = process.env.SESSION_SECRET;
  if (!secret || secret.length < 32) {
    throw new Error('[link] SESSION_SECRET must be set and at least 32 characters.');
  }
  return new TextEncoder().encode(secret);
}

/**
 * POST /api/tenant/auth/link
 *
 * Links an authenticated (but unlinked) User to a Tenant/Room record
 * using an invite code generated by the Owner during Move-In setup.
 *
 * Auth: Bearer <session-jwt>  (issued by the Tenant app's /api/auth/login proxy)
 * Body: { inviteCode: string }
 *
 * On success, returns the full session shape (same as /login):
 *  { userId, tenantId, roomId, roomNumber, fullName, email, linked: true }
 */
export async function POST(request: NextRequest) {
  try {
    // ── Verify Bearer token ──
    const authHeader = request.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const token = authHeader.slice(7).trim();
    let userId: string;
    let email: string;

    try {
      const secret = getSessionSecret();
      const { payload } = await jwtVerify<{ sub: string; email: string; linked: boolean }>(
        token,
        secret,
        { algorithms: ['HS256'] }
      );
      if (!payload.sub || !payload.email) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
      }
      userId = payload.sub;
      email = payload.email;
    } catch {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // ── Lookup user ──
    const user = await prisma.user.findFirst({
      where: { id: userId, email, role: 'TENANT' },
      include: { tenant: { include: { room: { select: { id: true, number: true } } } } },
    });

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // If already linked, return the existing session
    if (user.tenant) {
      return NextResponse.json({
        userId: user.id,
        tenantId: user.tenant.id,
        roomId: user.tenant.roomId,
        roomNumber: user.tenant.room.number,
        fullName: user.fullName,
        email: user.email,
        linked: true,
      });
    }

    // ── Parse invite code ──
    const body = await request.json();
    const validation = linkSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: 'กรุณากรอกรหัสเชื่อมห้อง' },
        { status: 400 },
      );
    }

    const { inviteCode } = validation.data;

    // ── Find tenant record with this invite code ──
    const tenantRecord = await prisma.tenant.findUnique({
      where: { inviteCode },
      include: { room: { select: { number: true } } },
    });

    if (!tenantRecord) {
      return NextResponse.json(
        { error: 'รหัสเชื่อมห้องไม่ถูกต้อง หรือถูกใช้ไปแล้ว' },
        { status: 404 },
      );
    }

    // ── Ensure room is not already claimed ──
    if (tenantRecord.userId !== null) {
      return NextResponse.json(
        { error: 'รหัสนี้ถูกใช้งานแล้ว กรุณาติดต่อเจ้าของหอพัก' },
        { status: 409 },
      );
    }

    // ── Link user → tenant record, consume the invite code ──
    const updatedTenant = await prisma.tenant.update({
      where: { id: tenantRecord.id },
      data: {
        userId: user.id,
        inviteCode: null, // Single-use — cleared immediately after claiming
      },
      include: { room: { select: { number: true } } },
    });

    return NextResponse.json({
      userId: user.id,
      tenantId: updatedTenant.id,
      roomId: updatedTenant.roomId,
      roomNumber: updatedTenant.room.number,
      fullName: user.fullName,
      email: user.email,
      linked: true,
    });
  } catch (error) {
    console.error('Link room error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
