import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import bcrypt from 'bcryptjs';
import { z } from 'zod';

const linkSchema = z.object({
  inviteCode: z.string().min(1),
});

/**
 * POST /api/tenant/auth/link
 *
 * Links an authenticated (but unlinked) User to a Tenant/Room record
 * using an invite code generated by the Owner during Move-In setup.
 *
 * Auth: Basic base64(email:password)
 * Body: { inviteCode: string }
 *
 * On success, returns the full session (same shape as /login):
 *  { userId, tenantId, roomId, roomNumber, fullName, email, linked: true }
 */
export async function POST(request: NextRequest) {
  try {
    const authHeader = request.headers.get('Authorization');
    if (!authHeader?.startsWith('Basic ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Decode credentials
    const decoded = Buffer.from(authHeader.slice(6), 'base64').toString('utf-8');
    const colonIdx = decoded.indexOf(':');
    if (colonIdx === -1) {
      return NextResponse.json({ error: 'Invalid credentials format' }, { status: 401 });
    }
    const email = decoded.slice(0, colonIdx);
    const password = decoded.slice(colonIdx + 1);

    // Verify user exists
    const user = await prisma.user.findUnique({
      where: { email },
      include: { tenant: true },
    });

    if (!user || user.role !== 'TENANT') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const isValid = await bcrypt.compare(password, user.passwordHash);
    if (!isValid) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // If already linked, just return the full session
    if (user.tenant) {
      const room = await prisma.room.findUnique({ where: { id: user.tenant.roomId } });
      return NextResponse.json({
        userId: user.id,
        tenantId: user.tenant.id,
        roomId: user.tenant.roomId,
        roomNumber: room?.number ?? '?',
        fullName: user.fullName,
        email: user.email,
        linked: true,
      });
    }

    // Parse invite code from body
    const body = await request.json();
    const validation = linkSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json(
        { error: 'กรุณากรอกรหัสเชื่อมห้อง' },
        { status: 400 },
      );
    }

    const { inviteCode } = validation.data;

    // Find the unlinked Tenant record with this invite code
    const tenantRecord = await prisma.tenant.findUnique({
      where: { inviteCode },
      include: { room: { select: { number: true } } },
    });

    if (!tenantRecord) {
      return NextResponse.json(
        { error: 'รหัสเชื่อมห้องไม่ถูกต้อง หรือถูกใช้ไปแล้ว' },
        { status: 404 },
      );
    }

    // Ensure room is not already linked to another user
    if (tenantRecord.userId !== null) {
      return NextResponse.json(
        { error: 'รหัสนี้ถูกใช้งานแล้ว กรุณาติดต่อเจ้าของหอพัก' },
        { status: 409 },
      );
    }

    // Link the user to the tenant record, clear the invite code
    const updatedTenant = await prisma.tenant.update({
      where: { id: tenantRecord.id },
      data: {
        userId: user.id,
        inviteCode: null, // Code is single-use — clear it after linking
      },
      include: { room: { select: { number: true } } },
    });

    return NextResponse.json({
      userId: user.id,
      tenantId: updatedTenant.id,
      roomId: updatedTenant.roomId,
      roomNumber: updatedTenant.room.number,
      fullName: user.fullName,
      email: user.email,
      linked: true,
    });
  } catch (error) {
    console.error('Link room error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
